### ISSUE TITLE
Plss update the mesa VirGl 

### ISSUE THREAD

**Issue by kedrick021** [alexvorxx/Mesa-VirGL#1]
Some game like dead island  have glitch graphics on Mali Mediatek Helio

**Comment by alexvorxx** [comment]
> Some game like dead island have glitch graphics on Mali Mediatek Helio

The latest versions of Mesa are unstable, DirectX tests and games do not work.

**Comment by kedrick021** [comment]
> > Some game like dead island have glitch graphics on Mali Mediatek Helio
> 
> The latest versions of Mesa are unstable, DirectX tests and games do not work.

I hope it fix soon

**Comment by alexvorxx** [comment]
> > > Some game like dead island have glitch graphics on Mali Mediatek Helio
> > 
> > 
> > The latest versions of Mesa are unstable, DirectX tests and games do not work.
> 
> I hope it fix soon

This problem is likely fixed in the new build.
https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.2a

**Comment by kedrick021** [comment]
> > > > Some game like dead island have glitch graphics on Mali Mediatek Helio
> > > 
> > > 
> > > The latest versions of Mesa are unstable, DirectX tests and games do not work.
> > 
> > 
> > I hope it fix soon
> 
> This problem is likely fixed in the new build. https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.2a

Crash the game

What Exagear I need to use 5 in 1?

**Comment by alexvorxx** [comment]
> > > > > Some game like dead island have glitch graphics on Mali Mediatek Helio
> > > > 
> > > > 
> > > > The latest versions of Mesa are unstable, DirectX tests and games do not work.
> > > 
> > > 
> > > I hope it fix soon
> > 
> > 
> > This problem is likely fixed in the new build. https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.2a
> 
> Crash the game
> 
> What Exagear I need to use 5 in 1?

Any. For example, the latest MultiWine AllMod or MultiWine Hugo.

**Comment by kedrick021** [comment]
> > > > > > Some game like dead island have glitch graphics on Mali Mediatek Helio
> > > > > 
> > > > > 
> > > > > The latest versions of Mesa are unstable, DirectX tests and games do not work.
> > > > 
> > > > 
> > > > I hope it fix soon
> > > 
> > > 
> > > This problem is likely fixed in the new build. https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.2a
> > 
> > 
> > Crash the game
> > What Exagear I need to use 5 in 1?
> 
> Any. For example, the latest MultiWine AllMod or MultiWine Hugo.

Still crash the game
After I put the mesa on multiwine hugo

**Comment by kedrick021** [comment]
> > > > > > > Some game like dead island have glitch graphics on Mali Mediatek Helio
> > > > > > 
> > > > > > 
> > > > > > The latest versions of Mesa are unstable, DirectX tests and games do not work.
> > > > > 
> > > > > 
> > > > > I hope it fix soon
> > > > 
> > > > 
> > > > This problem is likely fixed in the new build. https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.2a
> > > 
> > > 
> > > Crash the game
> > > What Exagear I need to use 5 in 1?
> > 
> > 
> > Any. For example, the latest MultiWine AllMod or MultiWine Hugo.
> 
> Still crash the game After I put the mesa on multiwine hugo

Even multiple wine all mod v7.5

**Comment by kedrick021** [comment]
Plss help when I use new mesa error say need directx 9 but I already installed
