### ISSUE TITLE
Plss need dxd11 for Mesa virgl 64bit

### ISSUE THREAD

**Issue by Renerosal01234** [alexvorxx/Mesa-VirGL#3]
64bit virgl are working but some game needs dxd10 or 11 plss update the mesa

**Comment by alexvorxx** [comment]
> 64bit virgl are working but some game needs dxd10 or 11 plss update the mesa

I'll try to update Mesa later.

**Comment by Renerosal01234** [comment]
> > 64bit virgl are working but some game needs dxd10 or 11 plss update the mesa
> 
> I'll try to update Mesa later.

You are the saviour of Mali phone thank you 😘

**Comment by alexvorxx** [comment]
> 64bit virgl are working but some game needs dxd10 or 11 plss update the mesa

Mesa code updated! The new release has been added.
https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.2b
