### ISSUE TITLE
Mesa Virgl Dx11 

### ISSUE THREAD

**Issue by mukul014** [alexvorxx/Mesa-VirGL#4]
Hi Sir. I've been using exagear for months for dx9 games. Is it true that your latest patch support dx10-11 for Virgl? I'm using mediatek helio p90 powerVR device. Also if you can help with me with issue too especially in Mafia 2 with Virgl built-in or overlay I'm having graphical bugs while other people on YouTube with Mali GPU having no bugs. What could be the issue? Thank you. 

I've downloaded the patch. So I just replaced them ? How would I select the patch inside exagear it has few different version. Like 18.0.3 
19.1 
21.2
22.1.7 and so on. 

Thank you once again.

**Comment by alexvorxx** [comment]
Hello. I haven't actually tested VirGL in DX10/11 games.  And I don't know about any patch.

**Comment by mukul014** [comment]
Hi thank you for response. I was referring to this update 
https://github.com/alexvorxx/Mesa-VirGL/issues/3 
Thank you. So I just wanted to know if virgl start supporting Dx11.

**Comment by mukul014** [comment]
> Hello. I haven't actually tested VirGL in DX10/11 games. And I don't know about any patch.

**Comment by alexvorxx** [comment]
> Hi thank you for response. I was referring to this update #3 Thank you. So I just wanted to know if virgl start supporting Dx11.

You can try the latest build.
https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.3a

About DX11. DX11 also depends on WineD3D. And I don't know what version of OpenGL and what extensions VirGL must support for DX11 to work.

**Comment by Gamd9** [comment]
> > Hi thank you for response. I was referring to this update #3 Thank you. So I just wanted to know if virgl start supporting Dx11.
> 
> You can try the latest build. https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.3a
> 
> About DX11. DX11 also depends on WineD3D. And I don't know what version of OpenGL and what extensions VirGL must support for DX11 to work.

It work just chang GL to 4.6 and chang GLSL to 120 or 330 some game need 120 other need 330 is work only in last mesa virgl and only work in wow64 version but fps is bad
