### ISSUE TITLE
Mesa-Virgl update for mobox

### ISSUE THREAD

**Issue by Petty441** [alexvorxx/Mesa-VirGL#5]
Hey Alex can you update the mesa of mobox for virgl or give me instructions to do it myself

**Comment by alexvorxx** [comment]
> Hey Alex can you update the mesa of mobox for virgl or give me instructions to do it myself

Hello. I don't know how to build Mesa for Mobox.
You'd better ask about it here:
https://github.com/olegos2/mobox

**Comment by Petty441** [comment]
Okay thanks for replying

**Comment by Petty441** [comment]
Okay thanks for replying

**Comment by Gamd9** [comment]
> Hey Alex can you update the mesa of mobox for virgl or give me instructions to do it myself

It work I  mobox just copy lib from last update in mobox lib
