### ISSUE TITLE
Update for virgl

### ISSUE THREAD

**Issue by MrPhryaNikFrosty** [alexvorxx/Mesa-VirGL#6]
Hello, is there any update for virgl. Because it have been 4 months didn't get the update

**Comment by alexvorxx** [comment]
> Hello, is there any update for virgl. Because it have been 4 months didn't get the update

Hello, virgl updated.
https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.3b

**Comment by MrPhryaNikFrosty** [comment]
Thanks alex ❤️

**Comment by MrPhryaNikFrosty** [comment]
> > Hello, is there any update for virgl. Because it have been 4 months didn't get the update
> 
> Hello, virgl updated. https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.3b

Thanks alex
