### ISSUE TITLE
How to compile Mesa Virgl for Winlator

### ISSUE THREAD

**Issue by Petty441** [alexvorxx/Mesa-VirGL#7]
Hey could you tell me how I can compile mesa virgl for Winlator or it's same command to compile mesa virgl for Winlator

**Comment by alexvorxx** [comment]
Hi. Unfortunately, I don't know how to compile mesa virgl for Winlator.

**Comment by Petty441** [comment]
I tried your builds but not working

**Comment by Petty441** [comment]
Can't do anything?

**Comment by alexvorxx** [comment]
> I tried your builds but not working

My builds are for Exagear only

**Comment by Petty441** [comment]
Bro please do something mali users stucked at old virgl in winlator

**Comment by alexvorxx** [comment]
> Bro please do something mali users stucked at old virgl in winlator

You'd better contact the Winlator developers.

**Comment by Petty441** [comment]
I tried bro but I can't there is no such way I can contact him there nothing about him not even issue option in winlator GitHub repository how do I contact him i tried many times but always failure

**Comment by alexvorxx** [comment]
> I tried bro but I can't there is no such way I can contact him there nothing about him not even issue option in winlator GitHub repository how do I contact him i tried many times but always failure

Try to ask this developer (Winlator with Native Glibc):
https://github.com/longjunyu2/winlator

This Winlator has VirGL.

**Comment by Petty441** [comment]
Yeah bro i already ask him and he said he will compile new virgl for he's upcoming winlator glibc version
